import {NgModule} from '@angular/core';
import {
    MatAutocompleteModule,
    MatBadgeModule,
    MatBottomSheetModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatCardModule,
    MatCheckboxModule,
    MatChipsModule,
    MatDatepickerModule,
    MatDialogModule,
    MatDividerModule,
    MatExpansionModule,
    MatFormFieldModule,
    MatGridListModule,
    MatIconModule,
    MatIconRegistry,
    MatInputModule,
    MatListModule,
    MatMenuModule,
    MatNativeDateModule,
    MatPaginatorModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatRadioModule,
    MatRippleModule,
    MatSelectModule,
    MatSidenavModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatSnackBarModule,
    MatSortModule,
    MatStepperModule,
    MatTableModule,
    MatTabsModule,
    MatToolbarModule,
    MatTooltipModule,
    MatTreeModule
} from '@angular/material';
import {DomSanitizer} from '@angular/platform-browser';


@NgModule({
    declarations: [],
    imports: [
        MatAutocompleteModule,
        MatBadgeModule,
        MatBottomSheetModule,
        MatButtonModule,
        MatButtonToggleModule,
        MatCardModule,
        MatCheckboxModule,
        MatFormFieldModule,
        MatChipsModule,
        MatDatepickerModule,
        MatDialogModule,
        MatDividerModule,
        MatExpansionModule,
        MatGridListModule,
        MatIconModule,
        MatInputModule,
        MatListModule,
        MatMenuModule,
        MatNativeDateModule,
        MatPaginatorModule,
        MatProgressBarModule,
        MatProgressSpinnerModule,
        MatRadioModule,
        MatRippleModule,
        MatSelectModule,
        MatSidenavModule,
        MatSliderModule,
        MatSlideToggleModule,
        MatSnackBarModule,
        MatSortModule,
        MatStepperModule,
        MatTableModule,
        MatTabsModule,
        MatToolbarModule,
        MatTooltipModule,
        MatTreeModule,
    ],
    exports: [
        MatAutocompleteModule,
        MatBadgeModule,
        MatBottomSheetModule,
        MatButtonModule,
        MatButtonToggleModule,
        MatCardModule,
        MatCheckboxModule,
        MatFormFieldModule,
        MatChipsModule,
        MatDatepickerModule,
        MatDialogModule,
        MatDividerModule,
        MatExpansionModule,
        MatGridListModule,
        MatIconModule,
        MatInputModule,
        MatListModule,
        MatMenuModule,
        MatNativeDateModule,
        MatPaginatorModule,
        MatProgressBarModule,
        MatProgressSpinnerModule,
        MatRadioModule,
        MatRippleModule,
        MatSelectModule,
        MatSidenavModule,
        MatSliderModule,
        MatSlideToggleModule,
        MatSnackBarModule,
        MatSortModule,
        MatStepperModule,
        MatTableModule,
        MatTabsModule,
        MatToolbarModule,
        MatTooltipModule,
        MatTreeModule,
    ]
})
export class MaterialModule {
    constructor(private matIconRegistry: MatIconRegistry, private domSanitizer: DomSanitizer) {

        this.matIconRegistry.addSvgIcon(
            `svg_user`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/user.svg')
        );

        this.matIconRegistry.addSvgIcon(
            `svg_basket`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/basket.svg')
        );

        this.matIconRegistry.addSvgIcon(
            `svg_logo`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/logo.svg')
        );

        this.matIconRegistry.addSvgIcon(
            `svg_logo_in_menu`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/logo_in_menu.svg')
        );

        this.matIconRegistry.addSvgIcon(
            `svg_home`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/home.svg')
        );

        this.matIconRegistry.addSvgIcon(
            `svg_categories`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/categories.svg')
        );


        this.matIconRegistry.addSvgIcon(
            `svg_list`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/list.svg')
        );

        this.matIconRegistry.addSvgIcon(
            `svg_address`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/address.svg')
        );

        this.matIconRegistry.addSvgIcon(
            `svg_logout`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/logout.svg')
        );

        this.matIconRegistry.addSvgIcon(
            `svg_rate_star`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/rate_star.svg')
        );

        this.matIconRegistry.addSvgIcon(
            `svg_sort`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/sort.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_producer`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/producer.svg')
        );

        this.matIconRegistry.addSvgIcon(
            `svg_default_image`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/default_image.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_add_to_basket`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/add_to_basket.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_add_to_basket_mini`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/add_to_basket_mini.svg')
        );

        this.matIconRegistry.addSvgIcon(
            `svg_basket_stepper_register_order`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/stepper_register_order.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_basket_stepper_choose_address`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/stepper_choose_address.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_basket_stepper_inquiries_from_pharmacy`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/stepper_inquiries_from_pharmacy.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_basket_stepper_finalize_purchase`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/stepper_finalize_purchase.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_arayeshi`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/arayeshi.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_otc`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/otc.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_pharmacy`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/pharmacy.svg')
        );

        this.matIconRegistry.addSvgIcon(
            `svg_on_demand`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/on_demand.svg')
        );

        this.matIconRegistry.addSvgIcon(
            `svg_search`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/search.svg')
        );

        this.matIconRegistry.addSvgIcon(
            `svg_add`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/add.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_danger`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/danger.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_check_circle`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/check_circle.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_map-add`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/map-add.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_pin`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/pin.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_dp_logo`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/dp_logo.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_edit`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/edit.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_done`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/done.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_provider`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/provider.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_sad`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/sad.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_like`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/like.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_dislike`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/dislike.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_add_comment`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/add_comment.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_outline_star`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/outline_star.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_baseline_star`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/baseline_star.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_pharmacy_default_banner`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/pharmacy_default_banner.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_club_member_tag`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/club_member_tag.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_subscribing_to_pharmacy`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/subscribing_to_pharmacy.svg')
        );

        this.matIconRegistry.addSvgIcon(
            `svg_arc`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/arc.svg')
        );

        this.matIconRegistry.addSvgIcon(
            `svg_why_daroopin_1`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/why_daroopin_1.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_why_daroopin_2`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/why_daroopin_2.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_why_daroopin_3`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/why_daroopin_3.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_why_daroopin_4`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/why_daroopin_4.svg')
        );

        this.matIconRegistry.addSvgIcon(
            `svg_bike`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/bike.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_sefaresh_az_darookhane`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/sefaresh_az_darookhane.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_help`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/help.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_address_map`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/address_map.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_selected_address_map`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/selected_address_map.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_warning`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/warning.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_pos`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/pos.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_transport`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/transport.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `svg_rate`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/rate.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `avatar-1`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/avatar-1.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `avatar-2`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/avatar-2.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `avatar-3`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/avatar-3.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `avatar-4`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/avatar-4.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `avatar-5`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/avatar-5.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `avatar-6`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/avatar-6.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `avatar-7`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/avatar-7.svg')
        );
        this.matIconRegistry.addSvgIcon(
            `avatar-8`,
            this.domSanitizer.bypassSecurityTrustResourceUrl('../assets/svgs/avatar-8.svg')
        );
    }
}
